### ISSUE TITLE
Question about timeout and killing the R process

### ISSUE THREAD

**Issue by hettling** [bricas/statistics-r#7]
Hi, 
I am using `Statistics::R` in my code and added a timeout for certain operations in R by overriding the `ALRM` signal. When I catch `ALRM` I would like to stop the R child process. However, `stop` waits until my R operation finished. I then kill the process manually. This works in general, but when my `Statistics::R` object goes out of scope and `DESTROY` is called, I get the error message 
`	(in cleanup) Error stopping R: 9` 
about the kill signal that I sent.  

Example:

    use strict;
    use warnings;
    use Statistics::R;

    my $R = Statistics::R->new;

    # timeout: 2 seconds
    my $timeout = 2;

    eval {
    	local $SIG{ALRM} = sub { die("Timed Out"); };
    	alarm($timeout);
    	# long-running command
    	$R->run("x <- mean(rt(100000000, df = 4))");
    	alarm(0);
    };

    if ($@) {
    	print $@;
        # kill process since $R->stop would wait until the R command finishes
    	kill 9, $R->pid;
    }

The error does no do any harm since my `$R` object is of scope anyways, but is there maybe a cleaner way to do this? Would it make sense to maybe check in `DESTROY` whether the pid of the child still exists (although this might be tricky for all platforms)? Or maybe even add such a timeout mechanism to the `run` subroutine?

Many thanks in advance, Best Regards,
Hannes

**Comment by fangly** [comment]
Hi Hettling,
Could you please try the latest development version of Statistics::R? I made some changes about a week ago that I think may fix this issue.
Cheers,
Florent

**Comment by hettling** [comment]
Hi Florent, 
if the development version is the most recent one from this repo, I am up-to date and still get the message about signal 9; I see that the latest commit is 2 weeks ago, so maybe I am missing something?

Thanks,
Hannes

**Comment by fangly** [comment]
Hi Hannes,

I would say that the behaviour of Statistics::R here is correct and expected here. Statistics::R normally returns an error message when the R process finishes unsuccessfully. Here you prevent the process from finishing successfully by interrupting it, and so Statistics::R does return an appropriate error message.

Since all the low level process management is done using IPC::Run, you could use $R->_bridge->kill_kill instead of kill to terminate the R process. It seems like IPC::Run also has timeout facilities that could be used by Statistics::R. So, if you want to add timeout facilities in Statistics::R, please go ahead and submit a patch!

Cheers,

Florent

**Comment by hettling** [comment]
Hi Florent,

I made an attempt to implement timeout functionality. I would be happy if you could review my pull request. 

Cheers,

Hannes

**Comment by fangly** [comment]
All done! Thank you Hannes.
